import { expect, openCleanEditor, test } from './fixtures'

test('supports seven-menu keyboard navigation, submenus, Escape, and focus return', async ({ page }) => {
  await openCleanEditor(page)
  const roots = page.getByTestId('menubar').getByRole('menuitem')
  await expect(roots).toHaveCount(7)
  await roots.nth(0).focus()
  await page.keyboard.press('ArrowRight')
  await expect(roots.nth(1)).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(roots.nth(0)).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menu', { name: '文件菜单' })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Escape')
  await expect(roots.nth(0)).toBeFocused()

  await page.getByRole('menuitem', { name: '插入' }).click()
  await page.getByRole('menuitem', { name: '矩形' }).click()
  await page.getByRole('menuitem', { name: '插入' }).click()
  await page.getByRole('menuitem', { name: '圆形' }).click()
  await page.getByRole('menuitem', { name: '编辑' }).click()
  await page.getByRole('menuitem', { name: '全选' }).click()
  await roots.nth(5).focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.submenu')).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menu', { name: '工具菜单' })).toBeHidden()
})

test('exposes icon labels/tooltips, contextual help, and trapped dialog focus', async ({ page }) => {
  await openCleanEditor(page)
  const icons = page.locator('button').filter({ hasText: /^(\?|×|−|□|«|»)$/ })
  const iconCount = await icons.count()
  expect(iconCount).toBeGreaterThan(0)
  for (let index = 0; index < iconCount; index += 1) {
    await expect(icons.nth(index)).toHaveAttribute('aria-label', /\S+/)
    await expect(icons.nth(index)).toHaveAttribute('title', /\S+/)
  }

  const helpTrigger = page.getByRole('button', { name: '形状库帮助' })
  await helpTrigger.click()
  await expect(page.getByRole('complementary', { name: '图元库帮助' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('complementary', { name: '图元库帮助' })).toBeHidden()
  await expect(helpTrigger).toBeFocused()

  await page.getByRole('menuitem', { name: '文件' }).click()
  await page.getByRole('menuitem', { name: '导出' }).click()
  const dialog = page.getByRole('dialog', { name: '导出' })
  await expect(dialog).toBeVisible()
  const first = dialog.getByTestId('export-help')
  const last = dialog.getByTestId('export-submit')
  await last.focus()
  await page.keyboard.press('Tab')
  await expect(first).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(last).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
})

test('keeps narrow layouts usable and exposes non-color state', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 700 })
  await openCleanEditor(page)
  await expect(page.getByTestId('right-panel')).toHaveClass(/floating/)
  await page.getByTestId('rp-close').click()
  await page.getByRole('button', { name: '折叠图元库' }).click()
  await expect(page.getByTestId('right-panel')).toBeHidden()
  await expect(page.getByRole('button', { name: '展开图元库' })).toBeVisible()
  const canvas = await page.getByTestId('x6-canvas').boundingBox()
  expect(canvas?.width).toBeGreaterThan(250)
  await expect(page.getByTestId('status-grid')).toHaveAttribute('aria-pressed', /true|false/)
  await expect(page.getByTestId('status-grid')).toContainText(/开|关/)
})

test('applies dark, forced-color, and reduced-motion preferences', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce', forcedColors: 'active' })
  await openCleanEditor(page)
  await expect.poll(() => page.evaluate(() => document.documentElement.dataset.theme)).toBe('dark')
  await expect.poll(() => page.evaluate(() => document.documentElement.dataset.reducedMotion)).toBe('reduce')
  expect(await page.evaluate(() => matchMedia('(forced-colors: active)').matches)).toBe(true)
  expect(await page.getByTestId('editor-shell').evaluate((element) => getComputedStyle(element).transitionDuration)).not.toBe('')
})
